version: "2"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - app1
    networks:
      - composite
    ports:
      - "80:80"
  app1:
    build:
      context: .
      dockerfile: server/Dockerfile
    networks:
      composite:
        aliases:
          - gofunserver
    ports:
      - "8080"
networks:
  composite:
