version: "2"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - app1
    networks:
      - composite
    ports:
      - "80:80"
    volumes:
      - './app/js/build:/var/www/assets/js'
  app1:
    build:
      context: .
      dockerfile: server/Dockerfile
    networks:
      composite:
        aliases:
          - gofunserver
    ports:
      - "8080"
    volumes:
      - './server:/go/src/github.com/gofun-server'
networks:
  composite:
